### ISSUE TITLE
Blank Prompt Window

### ISSUE THREAD

**Issue by wcatron** [peterfreeman/electron-osx-prompt#1]
Odd behavior. 

```
userPrompt('Please enter the verification code.', '').then(input => {
      console.log(input);
    }).catch(err => {
      console.log(err)
    })
```

<img width="646" alt="badprompt" src="https://user-images.githubusercontent.com/5385284/38377484-0ac8cb2a-38c9-11e8-88a1-75e3134d9348.png">

**Comment by peterfreeman** [comment]
Hey there,
to help me trying to reproduce and find the problem's source, could you please open the chrome dev tools and post any error messages here?
Are you opening the window from main or renderer process?

**Comment by wcatron** [comment]
Honestly, and I know this is super unhelpful, but I just went with a different package so I don’t have the code or any errors. I was calling it from the renderer process and I was using this boilerplate code: https://github.com/chentsulin/electron-react-boilerplate <https://github.com/chentsulin/electron-react-boilerplate>. Sorry I can’t be more helpful!

**Comment by peterfreeman** [comment]
Alright, I never tested the code when using React, I've always been going for Angular.
Seems that they don't play that well together so I'm closing this for now.

**Comment by OwenMelbz** [comment]
@wcatron are you able to share which package you went with in the end? I seem to have lost hours finding something suitable! We're in the same boat as you

thanks
